default_stages:
- commit

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: \.svg$

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.7.0
  hooks:
    - id: python-check-blanket-noqa

- repo: https://github.com/pycqa/flake8
  rev: '6.0.0'
  hooks:
    - id: flake8
      additional_dependencies: [
            'flake8-blind-except',
            'flake8-docstrings',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-implicit-str-concat',
            'pydocstyle>=5.0.0',
        ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
    - id: mypy
      additional_dependencies: [types-python-dateutil]
      entry: mypy .
      pass_filenames: false

- repo: https://github.com/best-doctor/pre-commit-hooks
  rev: 'v1.0.0'
  hooks:
    - id: mccabe-complexity
    - id: expr-complexity
    - id: no-asserts
      exclude: tests/
    - id: forbidden-imports

- repo: https://github.com/psf/black
  rev: '23.7.0'
  hooks:
    - id: black
      language_version: python

- repo: https://github.com/PyCQA/isort
  rev: '5.12.0'
  hooks:
    - id: isort
      args: ["--profile", "black"]

- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: '0.4.0' # the revision or tag to clone at
  hooks:
    - id: sync_with_poetry
      args: ['--all'] # optional args
